version: '3.8'
services:
  postgres-mcp:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_SSL_MODE=${DATABASE_SSL_MODE}
      - BEARER_TOKEN=${BEARER_TOKEN}
      - MCP_SERVER_HOST=0.0.0.0
      - MCP_SERVER_PORT=8000
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge